### ISSUE TITLE
A working example

### ISSUE THREAD

**Issue by nathobson** [kalasoo/NumberProgressBar#1]
Hi.

Perhaps I am being a bit slow or missing the point but do you have a working example where a a predefined number is reached rather than a randomly generated one? All of the examples seem random which doesn't help me understand how to properly use it for precise values. I looks great though!

Thanks,
Nat

**Comment by kalasoo** [comment]
Hi,

In the demo, the first section is purely random, which means each bar moves periodically, and the second one, apart from the initial animation, can be controlled by you with the buttons below (0, -10, -30, ..., 100). 
I'm so sorry for the confusion and I will update it later.

Regards,
Ming

**Comment by nathobson** [comment]
Hi Ming.

Thanks for your very swift reply.

My intended outcome (this happens to be very good timing for a project I'm working on) is to have several bars that all start at 0 and then animated up to a predefined number. Is this possible or have I confused the purpose?

Thanks,
Nat

**Comment by kalasoo** [comment]
Hi Nat,

Ya, this plugin is exactly what you want.
Take the following as an example.

HTML

``` html
<section id="bars">
  <div class="number-pb">
    <div class="number-pb-shown"></div>
    <div class="number-pb-num">0%</div>
  </div>
  ...
  <div class="number-pb">
    <div class="number-pb-shown"></div>
    <div class="number-pb-num">0%</div>
  </div>
</section>
```

JS

``` javascript
var bars = $('#bars .number-pb').NumberProgressBar().each(function() {
  $(this).reach(THE_NUM_YOU_WANT_THEM_TO_REACH);
});
```
